import React from 'react';
import { BiBold, BiCode, BiComment, BiImage, BiItalic, BiLink, BiListOl, BiListUl, BiPaperclip, BiStrikethrough, BiTable, BiUnderline, } from 'react-icons/bi';
import { v4 as uuid } from 'uuid';
export const toolbarConfig = {
    bold: {
        id: uuid(),
        tooltipText: 'Bold',
        icon: React.createElement(BiBold, null),
        format: 'bold',
        type: 'mark',
        'data-testId': 'bold-btn',
    },
    italic: {
        id: uuid(),
        tooltipText: 'Italics',
        icon: React.createElement(BiItalic, null),
        format: 'italic',
        type: 'mark',
        'data-testId': 'italic-btn',
    },
    code: {
        id: uuid(),
        tooltipText: 'Code',
        icon: React.createElement(BiCode, null),
        format: 'code',
        type: 'block',
        'data-testId': 'code-btn',
    },
    underline: {
        id: uuid(),
        tooltipText: 'Underline',
        icon: React.createElement(BiUnderline, null),
        format: 'underline',
        type: 'mark',
        'data-testId': 'underline-btn',
    },
    table: {
        id: uuid(),
        tooltipText: 'Table',
        icon: React.createElement(BiTable, null),
        format: 'table',
        type: 'block',
        'data-testId': 'table-btn',
    },
    'bulleted-list': {
        id: uuid(),
        tooltipText: 'UL',
        icon: React.createElement(BiListUl, null),
        format: 'bulleted-list',
        type: 'block',
        'data-testId': 'ul-btn',
    },
    'numbered-list': {
        id: uuid(),
        tooltipText: 'OL',
        icon: React.createElement(BiListOl, null),
        format: 'numbered-list',
        type: 'block',
        'data-testId': 'ol-btn',
    },
    image: {
        id: uuid(),
        tooltipText: 'Image',
        icon: React.createElement(BiImage, null),
        format: 'image',
        type: 'block',
        'data-testId': 'image-btn',
    },
    attachment: {
        id: uuid(),
        tooltipText: 'Attachment',
        icon: React.createElement(BiPaperclip, null),
        format: 'attachment',
        type: 'block',
        'data-testId': 'attachment-btn',
    },
    'block-quote': {
        id: uuid(),
        tooltipText: 'Quote',
        icon: React.createElement(BiComment, null),
        format: 'block-quote',
        type: 'block',
        'data-testId': 'quote-btn',
    },
    strikethrough: {
        id: uuid(),
        tooltipText: 'Strikethrough',
        icon: React.createElement(BiStrikethrough, null),
        format: 'strikethrough',
        type: 'mark',
        'data-testId': 'strikethrough-btn',
    },
    link: {
        id: uuid(),
        tooltipText: 'Link',
        icon: React.createElement(BiLink, null),
        format: 'link',
        type: 'block',
        'data-testId': 'link-btn',
    },
};
